name: Deploy to GitHub Pages

on:
  schedule:
    # Run every day at 7am Brisbane time (after GTFS update)
    - cron: '0 21 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'manifest.json'
      - 'icon-*.png'
      - 'icon.svg'
      - '.github/workflows/deploy-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Download and process GTFS data
        run: node process-gtfs.js
      
      - name: Create pages directory
        run: |
          mkdir -p _site
          cp index.html manifest.json icon-*.png icon.svg _site/
          cp -r data _site/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
